logging:
  log_freq: 50

datasets:
  dataset_file: 'coco'
  coco_path: 'data/COCO'
  batch_size: 6
  num_workers: 24

trainer:
  epochs: 300
  weight_decay: 1e-4
  lr: 1e-4
  lr_drop: 200
  clip_max_norm: 0.1
  output_dir: ''
  device: 'cuda'
  seed: 42
  resume_from_checkpoint: ''
  start_epoch: 0

distributed:
  world_size: 1
  dist_url: 'env://'

wandb:
  project: 'sparse-detector'
  entity: 'erikdao'
  dir: '.'
  save_code: true
  id: null
  job_type: 'train'
  allow_val_change: true
  tags: []