logging:
  log_freq: 50

wandb:
  project: 'sparse-detector'
  entity: 'erikdao'
  dir: '.'
  save_code: true
  id: null
  job_type: 'train'
  allow_val_change: true
  group: ''
  tags: []

datasets:
  dataset_file: 'coco'
  coco_path: 'data/COCO'
  batch_size: 6
  num_workers: 12

trainer:
  epochs: 300
  weight_decay: 0.1
  lr_drop: 200
  clip_max_norm: 0.1
  output_dir: ''
  device: 'cuda'
  seed: 42
  resume_from_checkpoint: ''
  start_epoch: 0
  world_size: 6
  dist_url: 'env://' 
  checkpoint_every: 20
