model:
  backbone:
    backbone: 'resnet50'
    lr_backbone: 1e-5
    dilation: false
    position_embedding: 'sine'
    return_interm_layers: true
  transformer:
    enc_layers: 6
    dec_layers: 6
    dim_feedforward: 2048
    hidden_dim: 256
    dropout: 0.1
    nheads: 8
    num_queries: 100
    pre_norm: true
    decoder_act: 'softmax'

loss:
  aux_loss: true
  matcher:
    set_cost_class: 1
    set_cost_bbox: 5
    set_cost_giou: 2
  coefficients:
    bbox_loss_coef: 5
    giou_loss_coef: 2
    eos_coef: 0.1
